trainer:
  gpus: 1
  max_epochs: 350 
  log_every_n_steps: 10
  check_val_every_n_epoch: 5
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch #step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss_epoch
        mode: min
        save_last: true
        filename: "DSEGait-casia-b-{epoch:02d}-{val_loss_epoch:.2f}"
model:
  #backend_name: StGCN 
  learning_rate: 0.01 
  loss_temperature: 0.07
  embedding_layer_size: 128
  tta: False
data:
  data_path: "data"  #"../data"
  batch_size: 128 # 64
  num_workers: 4 #8
  sequence_length: 60
